In [4]:
import  numpy as np

x=np.array([1,2,3,4,5])
x[-2]

4

In [6]:
x[3]= 65
x

array([ 1,  2,  3, 65,  5])

In [16]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#axis =1 means , y axis, 0 means 1st is removed
#axis =0 means , x axis, 0 means 1st is removed

In [17]:
y1=np.delete(arr,0,axis=1)
print(y1)


[[2 3]
 [5 6]
 [8 9]]


In [64]:
y1=np.delete(arr,0,axis=0)
y1

array([[4, 5, 6],
       [7, 8, 9]])

In [19]:
y1=np.delete(arr,[0,2],axis=1)
y1

array([[2],
       [5],
       [8]])

In [22]:
oned=np.array([1,2,3,4,5,6,7,8,9,10])
oned=np.delete(oned,[0,9])
oned

array([2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
oned=np.append(oned,[34,32])
oned


array([ 2,  3,  4,  5,  6,  7,  8,  9, 34, 32])

In [24]:
oned=np.insert(oned,2,[34,32])
oned

array([ 2,  3, 34, 32,  4,  5,  6,  7,  8,  9, 34, 32])

In [26]:
twod= np.arange(1,10).reshape(3,3)
twod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
twod=np.append(twod,[[23,45,65]],axis=0)
twod

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [23, 45, 65],
       [23, 45, 65]])

In [32]:
twod= np.append(twod,[[45],[45],[45],[45],[45]], axis=1)
twod

array([[ 1,  2,  3, 45],
       [ 4,  5,  6, 45],
       [ 7,  8,  9, 45],
       [23, 45, 65, 45],
       [23, 45, 65, 45]])

In [33]:
twod=np.insert(twod,2,87,axis=1)
twod

array([[ 1,  2, 87,  3, 45],
       [ 4,  5, 87,  6, 45],
       [ 7,  8, 87,  9, 45],
       [23, 45, 87, 65, 45],
       [23, 45, 87, 65, 45]])

In [36]:
a=np.array([1,2,3])
b=np.array([[4,3,5],[5,3,5]])
c=np.vstack((a,b))
c

array([[1, 2, 3],
       [4, 3, 5],
       [5, 3, 5]])

# Arithematic operations

In [37]:
x=np.random.randint(1,10,size=(3,3))
x

array([[6, 8, 1],
       [5, 9, 3],
       [9, 4, 3]])

In [38]:
y=np.random.randint(1,10,size=(3,3))
y

array([[9, 3, 2],
       [4, 2, 4],
       [8, 4, 5]])

In [39]:
x+y


array([[15, 11,  3],
       [ 9, 11,  7],
       [17,  8,  8]])

In [40]:
x*y


array([[54, 24,  2],
       [20, 18, 12],
       [72, 16, 15]])

In [41]:
np.exp(x)

array([[4.03428793e+02, 2.98095799e+03, 2.71828183e+00],
       [1.48413159e+02, 8.10308393e+03, 2.00855369e+01],
       [8.10308393e+03, 5.45981500e+01, 2.00855369e+01]])

In [42]:
np.sqrt(x)

array([[2.44948974, 2.82842712, 1.        ],
       [2.23606798, 3.        , 1.73205081],
       [3.        , 2.        , 1.73205081]])

In [43]:
np.power(x,2)

array([[36, 64,  1],
       [25, 81,  9],
       [81, 16,  9]])

In [44]:
x.mean()

5.333333333333333

In [45]:
x.mean(axis=0)

array([6.66666667, 7.        , 2.33333333])

In [46]:
x.std()

2.70801280154532

In [47]:
x.std(axis=0)

array([1.69967317, 2.1602469 , 0.94280904])

In [48]:
np.median(x)

5.0

In [50]:
x=np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
y=np.array([1,2,3,4])
y

array([1, 2, 3, 4])

In [52]:
y1=np.array([[1],[2],[3],[4]])
y1

array([[1],
       [2],
       [3],
       [4]])

In [53]:
y*y1

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

# Boolean Indexing

In [55]:
nos=np.arange(25).reshape(5,5)
nos

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
nos | nos > 20

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [58]:
nos [(nos>20) | (nos<15)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 21, 22,
       23, 24])

In [62]:
x=np.array([1,2,3,4,5,3,4,3,5])
y=np.array([6,7,8,2,4,2,5,4,3])
np.intersect1d(x,y)

array([2, 3, 4, 5])

In [63]:
x=np.arange(1,26).reshape(5,5)
x[x%2==1]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])