# Slicing
## [a:b]
### a is inclusive
### b is exclusive

In [8]:
import numpy as np
x=np.random.randint(1,10,size=(5,5))
x

array([[1, 3, 8, 7, 6],
       [9, 7, 5, 9, 3],
       [4, 1, 2, 5, 2],
       [3, 5, 6, 8, 7],
       [3, 5, 5, 3, 2]])

In [10]:
nos= x[:,:]
nos

array([[1, 3, 8, 7, 6],
       [9, 7, 5, 9, 3],
       [4, 1, 2, 5, 2],
       [3, 5, 6, 8, 7],
       [3, 5, 5, 3, 2]])

In [11]:
nos= x[2:,1:]
nos

array([[1, 2, 5, 2],
       [5, 6, 8, 7],
       [5, 5, 3, 2]])

In [13]:
nos= x[[1,3,4],:3]
nos

array([[9, 7, 5],
       [3, 5, 6],
       [3, 5, 5]])

In [14]:
np.diag(x, k=1)

array([3, 5, 5, 7])

In [15]:
np.diag(x, k=2)

array([8, 9, 2])

In [17]:
np.diag(x, k=0)


array([1, 7, 2, 8, 2])

## Sorting

In [20]:
nos= np.random.randint(1,5,size=(3,3))
nos

array([[4, 1, 4],
       [1, 1, 4],
       [4, 3, 1]])

In [21]:
np.sort(nos)

array([[1, 4, 4],
       [1, 1, 4],
       [1, 3, 4]])

In [24]:
np.sort(nos, axis=0)

array([[1, 4, 4],
       [1, 1, 4],
       [1, 3, 4]])